apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: lab-prometheus-stack
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=default"]
  generators:
    - list:
        elements:
        - name: in-cluster
          server: https://kubernetes.default.svc
  template:
    metadata:
      name: '{{.name}}-prometheus-stack'
    spec:
      project: default
      destination:
        server: '{{.server}}'
        namespace: monitoring
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
          - ApplyOutOfSyncOnly=true
      sources:
        - repoURL: https://prometheus-community.github.io/helm-charts
          chart: kube-prometheus-stack
          targetRevision: 55.7.0
          helm:
            releaseName: monitor
            valueFiles:
              # Reference: gitops-management
              - $values/testing/aws/us-east-1/data-plane/in-cluster/prometheus/apps/prometheus/default-prometheus.yaml
              - $values/testing/aws/us-east-1/data-plane/in-cluster/prometheus/apps/prometheus/exporters/default-exporters.yaml
              - $values/testing/aws/us-east-1/data-plane/in-cluster/prometheus/apps/prometheus/rules/default-rules.yaml
              # Reference: production-service-values
              - $values/apim/in-cluster/prometheus/prometheus.yaml
              - $values/apim/in-cluster/prometheus/rules/in-cluster-rules.yaml
              - $values/apim/in-cluster/prometheus/jobs/in-cluster-jobs.yaml
        # default values
        - repoURL: https://github.com/douglasgrande/argocd-prometheus-alertmanager.git
          targetRevision: lab-argocd-as-is-simulation
          ref: values