apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: lab-prometheus-stack
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=default"]
  generators:
    - list:
        elements:
        - name: in-cluster
          server: https://kubernetes.default.svc
  template:
    metadata:
      name: '{{.name}}-prometheus-stack'
    spec:
      project: default
      destination:
        server: '{{.server}}'
        namespace: monitoring
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
          - ApplyOutOfSyncOnly=true
      sources:
        - repoURL: https://prometheus-community.github.io/helm-charts
          chart: kube-prometheus-stack
          targetRevision: 55.7.0
          helm:
            releaseName: monitor
            valueFiles:
              - $values/values/prometheus/core-values/default-prometheus.yaml
              - $values/values/prometheus/custom-values/{{.name}}.yaml
              #- $values/values/prometheus/custom-values/rules/{{.name}}-rules.yaml
        # default values
        - repoURL: https://github.com/douglasgrande/argocd-prometheus-alertmanager.git
          targetRevision: HEAD
          ref: values