prometheus:
  prometheusSpec:
    additionalAlertManagerConfigs:
      - static_configs:
          - targets: [
            "http://lab-argocd-alertmanager.monitoring.svc.cluster.local:9093"
          ]
        scheme: https
