prometheus:
  prometheusSpec:
    additionalAlertManagerConfigs:
      - static_configs:
          - targets: [
            "lab-argocd-alertmanager.monitoring.svc.cluster.local:9091"
          ]
        scheme: http
